# only applies when running locally
app:
  host: 0.0.0.0
  port: 8080
  debug: true

db:
  name: test
  table: test

reservation:
  inventory_path: ../assets/hotel_information.json
  reservations_path: ../assets/reservations5.csv

logger:
  name: UpStay
  level: DEBUG